# Generated by Django 5.1.1 on 2024-09-19 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_remove_account_interests_accountprofile_interests"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountprofile",
            name="avatar",
            field=models.ImageField(default="avatar1.jpg", upload_to="avatars/"),
        ),
    ]
