# Generated by Django 5.1.1 on 2024-09-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_accountprofile_avatar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accountprofile",
            name="avatar",
        ),
        migrations.AddField(
            model_name="account",
            name="avatar",
            field=models.ImageField(default="avatar1.jpg", upload_to="avatars/"),
        ),
    ]
