# Generated by Django 5.1.1 on 2024-09-12 11:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="vote",
            old_name="vote_at",
            new_name="voted_at",
        ),
        migrations.RenameField(
            model_name="vote",
            old_name="vote_by",
            new_name="voted_by",
        ),
        migrations.AlterUniqueTogether(
            name="vote",
            unique_together={("poll", "voted_by")},
        ),
    ]
